# -*- coding: utf-8 -*-
"""FYP_Algorithims.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16JNNlUVIRr4VcUfwrmUbpdZHpjJNzvwK
"""

import numpy as np
import re
import string
import pandas as pd
import tensorflow as tf 
from gensim.models import Doc2Vec
from gensim.models.doc2vec import LabeledSentence
from gensim import utils
from nltk.corpus import stopwords
import numpy as np
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
from collections import Counter
import os
import keras
from keras import backend as K
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, Embedding, Input, RepeatVector
from keras.optimizers import SGD
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from nltk.stem import WordNetLemmatizer
import re
import inflect
import string
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
import nltk
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

"""#**Dataset Prepration & Visualization**"""

from google.colab import files
from google.colab import drive
drive.mount('/content/gdrive')

dataset_train = (r"/content/gdrive/MyDrive/Colab Notebooks/fyp/manual_label.csv")

df=pd.read_csv(dataset_train, encoding= 'unicode_escape')
df=df.fillna(' ')
df.count()

df.head()

l=df['Label'].value_counts()
print(l)
l0=l[0]
l1=l[1]

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.set_title('Labels of DataSet' )
Accuracy = ['Geuine Sellers','Dealers']
Algo = [l0,l1]
bars = plt.bar(Accuracy, height=Algo, width=.4)
for bar in bars:
    yval = round(bar.get_height())
    plt.text(bar.get_x()+0.1, yval + .5, yval,fontsize = 15, fontweight ='bold')
plt.show()

"""#**Pre-Processing**
### **NLP Pre-Processing Techniques**
"""

#Convert text to lowercase
def text_lowercase(text):
    return text.lower()

# Remove numbers
def remove_numbers(text):
    result = re.sub(r'\d+', '', text)
    return result

# numbers in words
p = inflect.engine()
# convert number into words
def convert_number(text):
    # split string into list of words
    temp_str = text.split()
    # initialise empty list
    new_string = []

    for word in temp_str:
        # if word is a digit, convert the digit
        # to numbers and append into the new_string list
        if word.isdigit():
            temp = p.number_to_words(word)
            new_string.append(temp)

        # append the word as it is
        else:
            new_string.append(word)

    # join the words of new_string to form a string
    temp_str = ' '.join(new_string)
    return temp_str

# remove punctuation
def remove_punctuation(text):
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

# White spaces removal
# remove whitespace from text
def remove_whitespace(text):
    return " ".join(text.split())

#Stop words removal
# remove stopwords function
def remove_stopwords(text):
    stop_words = set(stopwords.words("english"))
    word_tokens = word_tokenize(text)
    filtered_text = [word for word in word_tokens if word not in stop_words]
    return filtered_text

#Stemming using NLTK:
stemmer = PorterStemmer()
# stem words in the list of tokenised words
def stem_words(text):
    #word_tokens = word_tokenize(text)
    stems = [stemmer.stem(word) for word in text]
    return stems

#Lemmatization using NLTK:
lemmatizer = WordNetLemmatizer()
# lemmatize string
def lemmatize_word(text):
    #word_tokens = word_tokenize(text)
    # provide context i.e. part-of-speech
    lemmas = [lemmatizer.lemmatize(word, pos ='v') for word in text]
    return lemmas

def pre_Processing(in_string):
    input=in_string
    lc_string=text_lowercase(input)
    #rn_string=remove_numbers(lc_string)
    rp_string = remove_punctuation(lc_string)
    cn_string=convert_number(rp_string)
    rw_string=remove_whitespace(rp_string)
    rs_string=remove_stopwords(rw_string)
    #print(rs_string)
    sw_string=stem_words(rs_string)
    lemmatize_string=lemmatize_word(sw_string)
    #print(sw_string)
    return lemmatize_string

#df['text']=df['Owner Name']+ ' '+df['Contact Number']+ ' '+df['SellersComments']
df['text']=df['SellersComments']
df.head()

x=[]
x.append(df['text'].tolist())
#print(x[0])
#print(np.size(x))
x=x[0]

y=[]
for i in range (0,len(x)):
    #print(x[i])
    pre_processed=pre_Processing(x[i])
    pp_string=' '.join(map(str, pre_processed))
    y.append(pp_string)

df['text']=y
df.head()
df.to_csv('/content/gdrive/MyDrive/Colab Notebooks/fyp/MyDF.csv')

def split_data():
  data=df
  data=data.sample(frac=1).reset_index(drop=True)
  x = data.loc[:,'text'].values
  y = data.loc[:,'Label'].values

  train_size = int(0.8 * len(y))
  test_size = len(x) - train_size

  xtr = x[:train_size]
  xte = x[train_size:]
  ytr = y[:train_size]
  yte = y[train_size:]

  np.save('xtr_shuffled.npy',xtr)
  np.save('xte_shuffled.npy',xte)
  np.save('ytr_shuffled.npy',ytr)
  np.save('yte_shuffled.npy',yte)

def constructLabeledSentences(data):
    sentences = []
    for index, row in data.iteritems():
        sentences.append(LabeledSentence(utils.to_unicode(row).split(), ['Text' + '_%s' % str(index)]))
    return sentences

def getEmbeddings():
  data=df
  data=data.sample(frac=1).reset_index(drop=True)
  x = constructLabeledSentences(data['text'])
  y = data['Label'].values
  vector_dimension=300
  text_model = Doc2Vec(min_count=1, window=5, vector_size=vector_dimension, sample=1e-4, negative=5, workers=7, epochs=10,
                        seed=1)
  text_model.build_vocab(x)
  text_model.train(x, total_examples=text_model.corpus_count, epochs=text_model.iter)

  train_size = int(0.8 * len(x))
  test_size = len(x) - train_size

  text_train_arrays = np.zeros((train_size, vector_dimension))
  text_test_arrays = np.zeros((test_size, vector_dimension))
  train_labels = np.zeros(train_size)
  test_labels = np.zeros(test_size)

  for i in range(train_size):
      text_train_arrays[i] = text_model.docvecs['Text_' + str(i)]
      train_labels[i] = y[i]

  j = 0
  for i in range(train_size, train_size + test_size):
      text_test_arrays[j] = text_model.docvecs['Text_' + str(i)]
      test_labels[j] = y[i]
      j = j + 1

  return text_train_arrays, text_test_arrays, train_labels, test_labels

def plot_cmat(yte, ypred):
    cm = confusion_matrix(yte, ypred)
    plt.show()
    plt.figure(figsize=(6,6))
    sns.heatmap(cm, annot=True, fmt='d', xticklabels=['Geuine Sellers', 'Dealers'], yticklabels=['Geuine Sellers', 'Dealers'], cmap=plt.cm.Blues, cbar=False)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.show()



"""#***Text Classifier Using Doc2Vec Method***

##**Long-Short Term Memory (LSTM)**
"""

top_words = 5000
epoch_num = 25
batch_size = 16
split_data()
xtr = np.load('./xtr_shuffled.npy',allow_pickle=True)
xte = np.load('./xte_shuffled.npy',allow_pickle=True)
y_train = np.load('./ytr_shuffled.npy',allow_pickle=True)
y_test = np.load('./yte_shuffled.npy',allow_pickle=True)

cnt = Counter()
x_train = []
for x in xtr:
    x_train.append(x.split())
    for word in x_train[-1]:
        cnt[word] += 1  

# Storing most common words
most_common = cnt.most_common(top_words + 1)
word_bank = {}
id_num = 1
for word, freq in most_common:
    word_bank[word] = id_num
    id_num += 1

# Encode the sentences
for news in x_train:
    i = 0
    while i < len(news):
        if news[i] in word_bank:
            news[i] = word_bank[news[i]]
            i += 1
        else:
            del news[i]

y_train = list(y_train)
y_test = list(y_test)

# Delete the short news
i = 0
while i < len(x_train):
    if len(x_train[i]) > 10:
        i += 1
    else:
        del x_train[i]
        del y_train[i]

# Generating test data
x_test = []
for x in xte:
    x_test.append(x.split())

# Encode the sentences
for news in x_test:
    i = 0
    while i < len(news):
        if news[i] in word_bank:
            news[i] = word_bank[news[i]]
            i += 1
        else:
            del news[i]

# Truncate and pad input sequences
max_review_length = 100
X_train = sequence.pad_sequences(x_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(x_test, maxlen=max_review_length)

# Convert to numpy arrays
y_train = np.array(y_train)
y_test = np.array(y_test)

# Create the model
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(top_words+2, embedding_vecor_length, input_length=max_review_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
history=model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=epoch_num, batch_size=batch_size,verbose=2)
model.save('my_model.h5')
# list all data in history
print(history.history.keys())
# summarize history for accuracy
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=2)
print(scores)
acc_lstm=scores[1]*100
print("Accuracy= %.2f%%" % (acc_lstm))

# Draw the confusion matrix
y_pred = model.predict_classes(X_test)
plot_cmat(y_test, y_pred)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

"""##**Support Vector Machine (SVM)**"""

xtr,xte,ytr,yte = getEmbeddings()

# Use the built-in SVM for classification
clf = SVC()
clf.fit(xtr, ytr)
y_pred = clf.predict(xte)
m = yte.shape[0]
n = (yte != y_pred).sum()
acc_svm=(m-n)/m*100
print("Accuracy = ",acc_svm,"%")

# Draw the confusion matrix
plot_cmat(yte, y_pred)

"""##**Naive Bayes classifier**"""

# Use the built-in Naive Bayes classifier
gnb = GaussianNB()
gnb.fit(xtr,ytr)
y_pred = gnb.predict(xte)
m = yte.shape[0]
n = (yte != y_pred).sum()
acc_nb=(m-n)/m*100
print("Accuracy = ",acc_nb,"%")

# Draw the confusion matrix
plot_cmat(yte, y_pred)

"""##**Neural Network Using Keras**"""

def baseline_model():
    '''Neural network with 3 hidden layers'''
    model = Sequential()
    model.add(Dense(256, input_dim=300, activation='relu', kernel_initializer='normal'))
    model.add(Dropout(0.3))
    model.add(Dense(256, activation='relu', kernel_initializer='normal'))
    model.add(Dropout(0.5))
    model.add(Dense(80, activation='relu', kernel_initializer='normal'))
    model.add(Dense(2, activation="softmax", kernel_initializer='normal'))

    # gradient descent
    sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
    
    # configure the learning process of the model
    model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model

# Train the model
model_keras = baseline_model()
model_keras.summary()
x_train, x_test, y_train, y_test = train_test_split(xtr, ytr, test_size=0.2, random_state=42)
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y = np_utils.to_categorical((label_encoder.transform(y_train)))
label_encoder.fit(y_test)
encoded_y_test = np_utils.to_categorical((label_encoder.transform(y_test)))
history=model_keras.fit(x_train, encoded_y, validation_data=(x_test, encoded_y_test), epochs=30, batch_size=16)
#history = model.fit(x_train, encoded_y, epochs=25, batch_size=32)
print("Model Trained!")
score = model_keras.evaluate(x_test, encoded_y_test)
print("")
acc_keras=score[1]*100
print("Accuracy = " , acc_keras,"%")   
# list all data in history
print(history.history.keys())
# summarize history for accuracy
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
probabs = model_keras.predict_proba(x_test)
y_pred = np.argmax(probabs, axis=1)

# Draw the confusion matrix
plot_cmat(y_test, y_pred)

"""##**Comparison of Algorithims (Doc2Vec)**"""

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.set_title('Accuracy of Algorithims using Doc2Vec ' )
Accuracy = ['LSTM','SVM','NN with Keras', 'Navie Bayes']
Algo = [acc_lstm,acc_svm,acc_keras,acc_nb]
bars = plt.bar(Accuracy, height=Algo, width=.4)
for bar in bars:
    yval = round(bar.get_height())
    plt.text(bar.get_x()+0.1, yval + .5, yval,fontsize = 15, fontweight ='bold')
plt.show()

from tabulate import tabulate
l = [["LSTM",acc_lstm], ["SVM",acc_svm],["Neural Nework with Keras", acc_keras], ["Navie Bayes", acc_nb]]
table = tabulate(l, headers=['Algorithim', 'Accuracy'], tablefmt='orgtbl')
print(table)

"""#***Text Classifier Using TFIDF Vectorizer***

## ***SVM and Navie Baye***
"""

#Split DataSet for TF-IDF vectorizer
x_train,x_test,y_train,y_test=train_test_split(df['text'],df['Label'], test_size=0.2, random_state=7)
# tfidf vectorizer
tfidf_vectorizer=TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_train=tfidf_vectorizer.fit_transform(x_train)
tfidf_test=tfidf_vectorizer.transform(x_test)

# fit the training dataset on the classifier
SVM_tfidf = svm.SVC(C=1.0, kernel='rbf', degree=3, gamma='auto')
SVM_tfidf.fit(tfidf_train,y_train)
# predict the labels on validation dataset
predictions_SVM = SVM_tfidf.predict(tfidf_test)
# Use accuracy_score function to get the accuracy
acc_svm_tfidf=accuracy_score(predictions_SVM, y_test)*100
print("SVM Accuracy Score -> ",acc_svm_tfidf)

import joblib
filename = 'SVM_tfidf.sav'
joblib.dump(SVM_tfidf, filename)

Naive_tfidf = MultinomialNB()
Naive_tfidf.fit(tfidf_train,y_train)
# predict the labels on validation dataset
predictions_NB = Naive_tfidf.predict(tfidf_test)
# Use accuracy_score function to get the accuracy
acc_nb_tfidf=accuracy_score(predictions_NB, y_test)*100
print("Naive Bayes Accuracy Score -> ",acc_nb_tfidf)

import joblib
filename = 'Navie_tfidf.sav'
joblib.dump(Naive_tfidf, filename)

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.set_title('Accuracy of Algorithims using TF-IDF ' )
Accuracy = ['SVM','Navie Bayes']
Algo = [acc_svm_tfidf,acc_nb_tfidf]
bars = plt.bar(Accuracy, height=Algo, width=.2)
for bar in bars:
    yval = round(bar.get_height())
    plt.text(bar.get_x()+0.1, yval + .3, yval,fontsize = 15, fontweight ='bold')
plt.show()

from tabulate import tabulate
l = [["SVM",acc_svm_tfidf],["Navie Bayes", acc_nb_tfidf]]
table = tabulate(l, headers=['Algorithim', 'Accuracy'], tablefmt='orgtbl')
print(table)

"""##**Testing on few Examples**"""

import requests
from bs4 import BeautifulSoup
def Car_Data(url):
    pageLink=url
    # Step 1: Get the HTML
    r = requests.get(url)
    htmlContent = r.content

    # Step 2: Parse the HTML
    soup = BeautifulSoup(htmlContent, 'html.parser')
    #print(soup.prettify)
    # Step 3: HTML Tree traversal
    # Get the title of the HTML page
    title = soup.title.string
    title=str(title)
    split_string = title.split("20", 1)
    car_name = split_string[0]
    new_carname=car_name.split("19",1)
    car_name=new_carname[0]
    newnew_carname = car_name.split("18", 1)
    car_name = newnew_carname[0]
    #print(car_name)
    # Get all the Seller's Comments  from the page
    comment_class = soup.find('h2', id="scroll_seller_comments")
    comment_div = comment_class.find_next_sibling('div')
    #print(comment_class.text)
    sellers_comment=comment_div.text
    sellers_comment=str(sellers_comment)
    split_string = sellers_comment.split("Mention", 1)
    s_comment = split_string[0]
    #print(s_comment)
    #Get seller Information
    Owner_details = soup.findAll('div', {'class': 'seller-info'})
    Seller_Data=[]
    for owner_info in Owner_details:
        seller_data=owner_info.text
        Seller_Data=str(seller_data)

    word='Dealer:'
        #print(price_cell.text)
    #Get the Car deatils from web page
    details_class = soup.find('ul', id="scroll_car_detail")
    car_details=details_class.text
    car_details=car_details.split('\n')
    #print(car_details)

    #Price of Car
    Price_Info = soup.findAll('strong', {'class': 'generic-green'})
    Price_Car=[]
    for price in Price_Info:
        p_car=price.text
        Price_Car=p_car
    #print(Price_Car)
    #Get Car Info
    data = []
    table = soup.find('table', attrs={'class':"table table-bordered text-center table-engine-detail fs16"})
    table_body = table.find('tbody')

    rows = table_body.find_all('tr')
    for row in rows:
        cols = row.find_all('td')
        cols = [ele.text.strip() for ele in cols]
        data.append([ele for ele in cols if ele])
    #print(data)
    new_data=[]
    for i in data:
        new_data=i
    #print(new_data)
    #newRow=[title,sellers_comment]
    if word in Seller_Data:
        # print name and contact number
        owner_name=soup.findAll('label', {'itemprop':"name"})
        o_name=[]
        for owner_name in owner_name:
            seller_data=owner_name.text
            o_name=str(seller_data)
        #print(o_name)
        contact_number = soup.find('button', {'class': 'btn btn-block pull-left btn-phone'})
        number=contact_number['data-numbers']
        #print(number)
        data=car_name+' '+o_name+' '+number+' '+s_comment
        return data
    else:
        # print name and contact number
        owner_name=soup.find('h5',{'class':'nomargin'})
        owner=owner_name.text
        #print(owner)
        contact_number = soup.find('button', {'class': 'btn btn-block pull-left btn-phone'})
        number=contact_number['data-numbers']
        #print(number)
        #data=car_name+' '+owner+' '+number+' '+s_comment
        data=s_comment
        return data

url='https://www.pakwheels.com/used-cars/suzuki-baleno-2003-for-sale-in-lahore-5022373'
print(url)
test_sample=Car_Data(url)
pre_processed=pre_Processing(test_sample)
pp_string=' '.join(map(str, pre_processed))
tfidf_t=tfidf_vectorizer.transform([pp_string])

predict_svm=SVM_tfidf.predict(tfidf_t)
print("With SVM= ",predict_svm)

predict_nb=Naive_tfidf.predict(tfidf_t)
print('With NB= ', predict_nb)

"""#***Text Classifier using N-Gram Frequency Method***

## ***Navie Baye, LR and SVM Classifiers***
"""

from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics, svm
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition, ensemble

import pandas, xgboost, numpy, textblob, string
from keras.preprocessing import text, sequence
from keras import layers, models, optimizers

def train_model(classifier, feature_vector_train, label, feature_vector_valid, is_neural_net=False):
    # fit the training dataset on the classifier
    classifier.fit(feature_vector_train, label)
    
    # predict the labels on validation dataset
    predictions = classifier.predict(feature_vector_valid)
    
    if is_neural_net:
        predictions = predictions.argmax(axis=-1)
    
    return metrics.accuracy_score(predictions, valid_y)

# split the dataset into training and validation datasets 
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(df['text'], df['Label'])


# ngram level tf-idf 
tfidf_vect_ngram = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', ngram_range=(2,3), max_features=5000)
tfidf_vect_ngram.fit(df['text'])
xtrain_tfidf_ngram =  tfidf_vect_ngram.transform(train_x)
xvalid_tfidf_ngram =  tfidf_vect_ngram.transform(valid_x)

# Naive Bayes on Ngram Level TF IDF Vectors
accuracy = train_model(naive_bayes.MultinomialNB(), xtrain_tfidf_ngram, train_y, xvalid_tfidf_ngram)
print ("NB, N-Gram Vectors: ", accuracy)
# Linear Classifier on Ngram Level TF IDF Vectors
accuracy = train_model(linear_model.LogisticRegression(), xtrain_tfidf_ngram, train_y, xvalid_tfidf_ngram)
print ("LR, N-Gram Vectors: ", accuracy)
# SVM on Ngram Level TF IDF Vectors
accuracy = train_model(svm.SVC(), xtrain_tfidf_ngram, train_y, xvalid_tfidf_ngram)
print ("SVM, N-Gram Vectors: ", accuracy)

